language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-22.0.1
    - android-19
    - extra-google-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'intel-android-extra-license.+'

script: ./gradlew check
